### ISSUE TITLE
[PE-D] deletem command: exception thrown

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F09-4/tp#152]
Although this is mentioned in UG, you should handle the exception nicely anyway.

![image.png](https://raw.githubusercontent.com/fans2619/ped/main/files/ab0b3c98-faad-4ca0-aa32-1ae429eca9f2.png)

![image.png](https://raw.githubusercontent.com/fans2619/ped/main/files/a5f8e0f3-ccd9-4e3d-89b3-4307beeb8889.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: fans2619/ped#9

**Comment by Justinhoejj** [comment]
Duplicate #170
