### ISSUE TITLE
[PE-D] User Guide header appears twice on the website

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F09-4/tp#168]
User Guide header appears twice on the website.

![image.png](https://raw.githubusercontent.com/hanif-kamal/ped/main/files/df2d4108-6ef2-45e6-8c93-9b03b879f6ed.png)

Should be very simple to fix in Markdown.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: hanif-kamal/ped#12

**Comment by Jiwei99** [comment]
Same as #131
