### ISSUE TITLE
Implement Error Messages for Non-existent Dates 

### ISSUE THREAD

**Issue by leezhixuan** [AY2122S1-CS2103-F09-4/tp#50]
An error message should be shown to a user when they input a non-existent date such as 31st of February etc

**Comment by Justinhoejj** [comment]
![image](https://user-images.githubusercontent.com/68779715/136721562-1a2671a4-8bcf-44ac-8060-ac088e6245d9.png)
![image](https://user-images.githubusercontent.com/68779715/136721663-6d519589-6304-4cdd-81d1-56237e32a011.png)
