### ISSUE TITLE
Update DG 2, 3, 4

### ISSUE THREAD

**Issue by Justinhoejj** [AY2122S1-CS2103-F09-4/tp#7]
- Use cases: Give use cases (textual form) for a few representative user stories that need multiple steps to complete. e.g. Adding a tag to a person (assume the user needs to find the person first)

- Non-functional requirements: Note: Many of the given project constraints can be considered NFRs. You can add more. e.g. performance requirements, usability requirements, scalability requirements, etc.

- Glossary: Define terms that are worth recording.

**Comment by leezhixuan** [comment]
done sir, please review my PR
